name: CI
on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - '*'
  pull_request:
jobs:
  libcore:
    name: Native Build (LibCore)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Native Build
        run: ./run lib core
      - name: Upload Libcore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libcore-aar
          path: app/libs/libcore.aar

  build:
    name: Build OSS APK
    runs-on: ubuntu-latest
    needs:
      - libcore
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download Libcore Artifact
        uses: actions/download-artifact@v4
        with:
          name: libcore-aar
          path: app/libs
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-oss-${{ hashFiles('**/*.gradle.kts') }}-ci
      - name: Gradle Build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/25.0.8775105" >> local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action gradle
          ./gradlew app:assembleOssDebug
          APK=$(find app/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname $APK)
          echo "APK=$APK" >> $GITHUB_ENV
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: ${{ env.APK }}